### ISSUE TITLE
Document how `CredentialOptions` can be serialized

### ISSUE THREAD

**Issue by Infinisil** [tweag/webauthn#103]
In case the server wants to store it persistently, not just in memory. These docs should just mention that the server needs to store everything needed to reproduce the options, which certainly has to include the challenge, but doesn't have to include fields that are always set to a constant.

**Comment by Infinisil** [comment]
From the discussion with @lykahb in https://github.com/tweag/webauthn/pull/113#discussion_r790700382 I have the feeling that it makes sense to introduce a new type, perhaps called `PendingCredentialOptions`, which is like a `CredentialOptions`, but limited to only the fields necessary for finishing the respective ceremony. That is:

For registration:
- `corChallenge`
- `ascUserVerification . corAuthenticatorSelection`
- `corPubKeyCredParams`
- `corUser` (technically only the `cueId` is needed, but the other fields are needed by the server to create the user once registration is finished)

For authentication:
- `coaChallenge`
- `coaUserVerification`
- `coaAllowCredentials`

This type then can be made serializable by the server as needed without storing extra information. This also makes it more efficient to store this structure in memory.

**Comment by lykahb** [comment]
Adding the fields from this issue description to the documentation of `CredentialOptions` would be make it clear what is necessary to store.

As the first user of this library, I think that it is too early to write the convenience data types and functions. It is easier to start working with a bare-bones API than with a larger one that takes more time to learn has helpers that may not match the use case.
