### ISSUE TITLE
Full Support for WebAuthn 2?

### ISSUE THREAD

**Issue by ohri-anurag** [tweag/webauthn#122]
### Discussed in https://github.com/tweag/webauthn/discussions/121

<div type='discussions-op-text'>

<sup>Originally posted by **ohri-anurag** January 28, 2022</sup>
Hi,

I came across this library while searching for Haskell versions of the WebAuthn spec. I have following the repo's progress for the past few weeks, I see that it is actively being worked on. Thanks a lot for building this.

I want to know if this library has full support for WebAuthn 2. If not, are there any plans to support the full spec in the future?

Regards,
Anurag Ohri</div>

**Comment by ErinvanderVeen** [comment]
Answered in #121
