### ISSUE TITLE
GHC 9.2 compatibility

### ISSUE THREAD

**Issue by arybczak** [tweag/webauthn#152]
It seems that getting this to build with GHC 9.2 is non-trivial.

- `cborg` doesn't compile, though it should be easy to fix.
- `singletons` probably also don't compile.

**Comment by infinisil** [comment]
Thanks for the pointer! It looks like some bound updates were needed, but with those I was able to make it work with GHC 9.2, check out the PR and let me know whether it works for you: https://github.com/tweag/webauthn/pull/153

**Comment by arybczak** [comment]
Thanks for such a fast response! Apparently my approach wasn't very good, I yolo'd into things with `allow-newer: *` and got a `cborg` compilation failure. The PR works for me :+1: 

If you could also make a release with this fix, it would be lovely :slightly_smiling_face:

**Comment by infinisil** [comment]
Awesome, https://hackage.haskell.org/package/webauthn-0.4.1.1 is released :)
