### ISSUE TITLE
Support other attestation formats

### ISSUE THREAD

**Issue by ErinvanderVeen** [tweag/webauthn#16]
The full list of webauthn attestation formats is [maintained by the iana](https://www.iana.org/assignments/webauthn/webauthn.xhtml) (with the exception of the "none" and "apple" formats). The specification of the different formats can be found in [chapter 8](https://www.w3.org/TR/webauthn-2/#sctn-defined-attestation-formats) of the webauthn specification. The attestation verification currently happens in `Crypto.Fido.Attestation`.

**Comment by Infinisil** [comment]
Since #67 we're only missing `android-safetynet`

**Comment by ErinvanderVeen** [comment]
A branch exists called `android-safetynet` that starts this implementation, although it is already a little out of date.

**Comment by ErinvanderVeen** [comment]
Android SafetyNet has been merged with #79
