### ISSUE TITLE
Attestation certificate without AAGUID extension is rejected

### ISSUE THREAD

**Issue by stephenjudkins** [tweag/webauthn#173]
**Describe the bug**
The spec that the AAGUID extension is optional: https://w3c.github.io/webauthn/#sctn-packed-attestation-cert-requirements

However, this library will not parse an attestation statement where it is missing: https://github.com/tweag/webauthn/blob/f0d8046fe85d9165d2dd6b4325319f99b548b022/src/Crypto/WebAuthn/AttestationStatementFormat/Packed.hs#L117

**To Reproduce**
Create an registration requests with an attestation statement (using a library like https://github.com/kanidm/webauthn-rs/) without the AAGUID extension. Attempt to go through the registration flow using this library. You will receive a `Certificate aaguid extension is missing` error.

**Expected behavior**
The registration flow should succeed despite lack of AAGUID extension in the x509 certificate.

**Environment**
 - OS name + version: macos and linux
 - Version of the code `0.6.0.1`

**Comment by ErinvanderVeen** [comment]
Hej! Thank you for reporting this, apparently we missed it.

We'll try to publish a fix as soon as possible

**Comment by ErinvanderVeen** [comment]
NOTE: This library implements version 2 of the spec, but that one also appears to mark the AAGUID extension as optional.

**Comment by stephenjudkins** [comment]
Greatly appreciate it, thank you!

**Comment by infinisil** [comment]
This is now released in [webauthn-0.7.0.0](https://hackage.haskell.org/package/webauthn-0.7.0.0) (thanks for doing the release @ErinvanderVeen)

**Comment by stephenjudkins** [comment]
You all rule!
