### ISSUE TITLE
Don't use x509-validation fork

### ISSUE THREAD

**Issue by Infinisil** [tweag/webauthn#75]
We're currently using the x509-validation fork from https://github.com/vincenthz/hs-certificate/pull/126 in order to have a pure function to do X.509 verification. However we need to upload this library to [Hackage](https://hackage.haskell.org/), which can't work with this. So we need to do one of these things, ordered from most to least preferred:

- Get the PR merged and a new `x509-validation` release published by @vincenthz
- Copy the pure validation code from x509-validation library into our own source code and use that instead
- Make this library have its main functions be in IO

https://github.com/tweag/haskell-fido2/blob/44e89a1519b7d9a809209a3e4907daf782091650/cabal.project#L3-L10

**Comment by ErinvanderVeen** [comment]
The PR has just been merged, but we do need to do version bumb and ask for a re-upload to hackage.
