### ISSUE TITLE
Upload to Hackage

### ISSUE THREAD

**Issue by Infinisil** [tweag/webauthn#78]
In https://github.com/tweag/webauthn/pull/62#issuecomment-989675180, @fumieval offered to give us upload rights for the [webauthn](https://hackage.haskell.org/package/webauthn) Hackage package currently owned by him with his implementation in https://github.com/fumieval/webauthn, so that we can upload this version once ready.

Hoping @fumieval sees this issue, my Hackage username is [infinisil](https://hackage.haskell.org/user/infinisil). We're planning to upload the package in the following weeks.

Currently blocking for a Hackage upload however is #75

**Comment by fumieval** [comment]
I've just added `infinisil` as a maintainer for `webauthn`

**Comment by Infinisil** [comment]
Thanks!

**Comment by arianvp** [comment]
Do we want to write a little announcement blog post as well? Perhaps with a bit of history how this all got to fruition? (Started as hackathon project at Zurihac etc.)

**Comment by Infinisil** [comment]
The first release has just been published! https://hackage.haskell.org/package/webauthn-0.1.0.0

Yes we'll write a blog post announcing this soon :)
